language: node_js
node_js:
  - "9.3.0"
services:
  - mongodb
branches:
  only:
    - master
cache:
  directories:
    - node_modules
# before_script:
#   - sleep 15
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - "yarn install"

# after_success: yarn coverage
after_success: 
  - yarn coverage
  - yarn coverage:codecov